//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACW_Client.HostTalkback {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Host")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HostTalkback.ITalkbackService")]
    public interface ITalkbackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITalkbackService/server_reply", ReplyAction="http://tempuri.org/ITalkbackService/server_replyResponse")]
        string server_reply();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITalkbackService/server_reply", ReplyAction="http://tempuri.org/ITalkbackService/server_replyResponse")]
        System.Threading.Tasks.Task<string> server_replyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITalkbackService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITalkbackService/GetDataUsingDataContractResponse")]
        ACW_Client.HostTalkback.CompositeType GetDataUsingDataContract(ACW_Client.HostTalkback.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITalkbackService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITalkbackService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ACW_Client.HostTalkback.CompositeType> GetDataUsingDataContractAsync(ACW_Client.HostTalkback.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITalkbackServiceChannel : ACW_Client.HostTalkback.ITalkbackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TalkbackServiceClient : System.ServiceModel.ClientBase<ACW_Client.HostTalkback.ITalkbackService>, ACW_Client.HostTalkback.ITalkbackService {
        
        public TalkbackServiceClient() {
        }
        
        public TalkbackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TalkbackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TalkbackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TalkbackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string server_reply() {
            return base.Channel.server_reply();
        }
        
        public System.Threading.Tasks.Task<string> server_replyAsync() {
            return base.Channel.server_replyAsync();
        }
        
        public ACW_Client.HostTalkback.CompositeType GetDataUsingDataContract(ACW_Client.HostTalkback.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ACW_Client.HostTalkback.CompositeType> GetDataUsingDataContractAsync(ACW_Client.HostTalkback.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
